package com.gtohjs.item;

import com.gtohjs.util.ModLog;
import net.minecraft.resources.ResourceLocation;
import net.minecraftforge.fml.loading.FMLPaths;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.AtomicMoveNotSupportedException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import java.util.UUID;

public final class RecipeDraftWriter {
    private static final DateTimeFormatter FILE_TIME = DateTimeFormatter.ofPattern("yyyyMMdd-HHmmss-SSS");
    private static final DateTimeFormatter COMMENT_TIME = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

    private RecipeDraftWriter() {
    }

    public static Path write(ResourceLocation machineId, ResourceLocation recipeTypeId,
                             String recipeId, String builderSource) throws IOException {
        Path gameDirectory = FMLPaths.GAMEDIR.get().toAbsolutePath().normalize();
        Path outputDirectory = gameDirectory.resolve("gtohjs").resolve("recipes").normalize();
        if (!outputDirectory.startsWith(gameDirectory)) {
            throw new IOException("Recipe draft directory escaped the game directory");
        }
        Files.createDirectories(outputDirectory);

        LocalDateTime now = LocalDateTime.now();
        String randomSuffix = UUID.randomUUID().toString().substring(0, 8);
        String fileName = sanitize(machineId.toString()) + "__" + sanitize(recipeId) + "__" +
                FILE_TIME.format(now) + "-" + randomSuffix + ".java";
        Path target = outputDirectory.resolve(fileName).normalize();
        if (!target.getParent().equals(outputDirectory)) {
            throw new IOException("Invalid recipe draft file name");
        }

        String document = "// Generated by GTOHJS Recipe Editor at " + COMMENT_TIME.format(now) + "\n" +
                "// Target machine: " + machineId + "\n" +
                "// Recipe type: " + recipeTypeId + "\n" +
                "// Recipe id: " + recipeId + "\n" +
                "// Source draft: review this fragment before adding it to GTOHJS.\n\n" +
                builderSource.strip() + "\n";

        Path temporary = Files.createTempFile(outputDirectory, ".gtohjs-recipe-", ".tmp");
        try {
            Files.writeString(temporary, document, StandardCharsets.UTF_8);
            try {
                Files.move(temporary, target, StandardCopyOption.ATOMIC_MOVE);
            } catch (AtomicMoveNotSupportedException ignored) {
                Files.move(temporary, target);
            }
        } finally {
            Files.deleteIfExists(temporary);
        }

        ModLog.info("Generated recipe source draft {}; machine={}, recipeType={}, recipeId={}",
                target, machineId, recipeTypeId, recipeId);
        return target;
    }

    static String sanitize(String value) {
        String result = value.toLowerCase(Locale.ROOT).replaceAll("[^a-z0-9._-]+", "_");
        result = result.replaceAll("^\\.+", "").replaceAll("\\.+$", "");
        return result.isEmpty() ? "recipe" : result;
    }
}
