package com.gtohjs.item;

import com.gtohjs.util.ModLog;
import net.minecraft.resources.ResourceLocation;
import net.minecraftforge.fml.loading.FMLPaths;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.AtomicMoveNotSupportedException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

public final class RecipeDraftWriter {
    private static final DateTimeFormatter COMMENT_TIME = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

    private RecipeDraftWriter() {
    }

    public static Path write(ResourceLocation machineId, ResourceLocation recipeTypeId,
                             String recipeId, String className, String source) throws IOException {
        if (className == null || !className.matches("[A-Za-z_$][A-Za-z0-9_$]*")) {
            throw new IOException("Invalid generated Java class name: " + className);
        }
        Path gameDirectory = FMLPaths.GAMEDIR.get().toAbsolutePath().normalize();
        Path outputDirectory = gameDirectory.resolve("gtohjs").resolve("recipe").normalize();
        if (!outputDirectory.startsWith(gameDirectory)) {
            throw new IOException("Recipe draft directory escaped the game directory");
        }
        Files.createDirectories(outputDirectory);

        LocalDateTime now = LocalDateTime.now();
        String fileName = className + ".java";
        Path target = outputDirectory.resolve(fileName).normalize();
        if (!target.getParent().equals(outputDirectory)) {
            throw new IOException("Invalid recipe draft file name");
        }

        if (Files.exists(target)) {
            throw new IOException("Generated recipe class already exists: " + target.getFileName());
        }

        String document = "// Generated by GTOHJS Recipe Editor at " + COMMENT_TIME.format(now) + "\n" +
                "// Target machine: " + machineId + "\n" +
                "// Recipe type: " + recipeTypeId + "\n" +
                "// Recipe id: " + recipeId + "\n" +
                "// Copy this complete class to src/main/java/com/gtohjs/gtrecipe before rebuilding.\n\n" +
                source.strip() + "\n";

        Path temporary = Files.createTempFile(outputDirectory, ".gtohjs-recipe-", ".tmp");
        try {
            Files.writeString(temporary, document, StandardCharsets.UTF_8);
            try {
                Files.move(temporary, target, StandardCopyOption.ATOMIC_MOVE);
            } catch (AtomicMoveNotSupportedException ignored) {
                Files.move(temporary, target);
            }
        } finally {
            Files.deleteIfExists(temporary);
        }

        ModLog.info("Generated complete recipe source {}; machine={}, recipeType={}, recipeId={}",
                target, machineId, recipeTypeId, recipeId);
        return target;
    }
}
