package com.gtohjs.item;

import com.gtohjs.util.ModLog;
import net.minecraft.resources.ResourceLocation;
import net.minecraftforge.fml.loading.FMLPaths;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.AtomicMoveNotSupportedException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import java.util.UUID;

/** Writes structure-generator output outside the mod jar so it can be reviewed and edited. */
public final class StructureDraftWriter {
    private static final DateTimeFormatter FILE_TIME = DateTimeFormatter.ofPattern("yyyyMMdd-HHmmss-SSS");
    private static final DateTimeFormatter COMMENT_TIME = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

    private StructureDraftWriter() {
    }

    /** Identity is created once so the generated class and file use the same stem. */
    public record DraftIdentity(ResourceLocation machineId, String fileStem,
                                String className, LocalDateTime createdAt) {
    }

    public static DraftIdentity createIdentity(ResourceLocation machineId) {
        LocalDateTime now = LocalDateTime.now();
        String randomSuffix = UUID.randomUUID().toString().substring(0, 8);
        String fileStem = sanitize(machineId.toString()) + "__" + FILE_TIME.format(now) + "-" + randomSuffix;
        return new DraftIdentity(machineId, fileStem, "GtohjsStructureDraft_" + javaIdentifier(fileStem), now);
    }

    public static Path write(DraftIdentity identity, int minX, int minY, int minZ,
                             int maxX, int maxY, int maxZ, ResourceLocation placeholderBlock,
                             String blockMapping, String source) throws IOException {
        Path gameDirectory = FMLPaths.GAMEDIR.get().toAbsolutePath().normalize();
        Path outputDirectory = gameDirectory.resolve("gtohjs").resolve("structures").normalize();
        if (!outputDirectory.startsWith(gameDirectory)) {
            throw new IOException("Structure draft directory escaped the game directory");
        }
        Files.createDirectories(outputDirectory);

        LocalDateTime now = identity.createdAt();
        String machineId = identity.machineId().toString();
        String fileName = identity.className() + ".java";
        Path target = outputDirectory.resolve(fileName).normalize();
        if (!target.getParent().equals(outputDirectory)) {
            throw new IOException("Invalid structure draft file name");
        }

        StringBuilder document = new StringBuilder()
                .append("// Generated by GTOHJS Multiblock Structure Generator at ")
                .append(COMMENT_TIME.format(now)).append('\n')
                .append("// Target machine: ").append(machineId).append('\n')
                .append("// Bounds: [").append(minX).append(", ").append(minY).append(", ").append(minZ)
                .append("] -> [").append(maxX).append(", ").append(maxY).append(", ").append(maxZ).append("]\n")
                .append("// Size: ").append(maxX - minX + 1).append(" x ")
                .append(maxY - minY + 1).append(" x ").append(maxZ - minZ + 1).append('\n')
                .append("// Controller placeholder: ").append(placeholderBlock).append('\n')
                .append("// Air positions are emitted as spaces and matched by Predicates.any().\n")
                .append("// Block mapping:\n").append(blockMapping)
                .append("\n")
                .append(source.strip()).append('\n');

        Path temporary = Files.createTempFile(outputDirectory, ".gtohjs-structure-", ".tmp");
        try {
            Files.writeString(temporary, document, StandardCharsets.UTF_8);
            try {
                Files.move(temporary, target, StandardCopyOption.ATOMIC_MOVE);
            } catch (AtomicMoveNotSupportedException ignored) {
                Files.move(temporary, target);
            }
        } finally {
            Files.deleteIfExists(temporary);
        }
        ModLog.info("Generated structure source draft {}; machine={}, placeholder={}, size={}x{}x{}",
                target, machineId, placeholderBlock, maxX - minX + 1, maxY - minY + 1, maxZ - minZ + 1);
        return target;
    }

    private static String javaIdentifier(String value) {
        StringBuilder result = new StringBuilder(value.length() + 1);
        for (int index = 0; index < value.length(); index++) {
            char character = value.charAt(index);
            if (index == 0 && !Character.isJavaIdentifierStart(character)) {
                result.append('_');
            }
            result.append(Character.isJavaIdentifierPart(character) ? character : '_');
        }
        return result.toString();
    }

    static String sanitize(String value) {
        String result = value.toLowerCase(Locale.ROOT).replaceAll("[^a-z0-9._-]+", "_");
        result = result.replaceAll("^\\.+", "").replaceAll("\\.+$", "");
        return result.isEmpty() ? "structure" : result;
    }
}
