// Generated by GTOHJS Recipe Editor at 2026-09-10 00:18:13
// Target machine: minecraft:crafting_table
// Recipe type: minecraft:crafting
// Recipe id: ozonation_purification_unit
// Copy this complete class to src/main/java/com/gtohjs/gtrecipe before rebuilding.

package com.gtohjs.gtrecipe;

import com.gregtechceu.gtceu.data.recipe.VanillaRecipeHelper;
import com.gtohjs.api.CraftingRecipeSource;
import com.gtohjs.api.RecipeSourceSupport;
import java.util.Collection;
import java.util.List;
import net.minecraft.resources.ResourceLocation;

/** Generated method-mode shaped crafting recipe. */
public final class GeneratedOzonationPurificationUnitRecipe6f_7a_6f_6e_61_74_69_6f_6e_5f_70_75_72_69_66_69_63_61_74_69_6f_6e_5f_75_6e_69_74_ implements CraftingRecipeSource {
    private static final ResourceLocation RAW_ID = new ResourceLocation("gtohjs", "ozonation_purification_unit");

    public GeneratedOzonationPurificationUnitRecipe6f_7a_6f_6e_61_74_69_6f_6e_5f_70_75_72_69_66_69_63_61_74_69_6f_6e_5f_75_6e_69_74_() {}

    @Override public Collection<ResourceLocation> rawIds() { return List.of(RAW_ID); }

    @Override public void register() {
        VanillaRecipeHelper.addShapedRecipe(
                RAW_ID,
                RecipeSourceSupport.itemStack("gtocore:ozonation_purification_unit", 1, ""),
                "A  ",
                "   ",
                "   ",
                'A', RecipeSourceSupport.itemStack("gtocore:clarifier_purification_unit", 1, ""));
    }
}
