// Generated by GTOHJS Recipe Editor at 2026-09-10 00:17:38
// Target machine: gtceu:lv_lathe
// Recipe type: gtceu:lathe
// Recipe id: clarifier_purification_unit
// Copy this complete class to src/main/java/com/gtohjs/gtrecipe before rebuilding.

package com.gtohjs.gtrecipe;

import com.gtohjs.api.GTRecipeSource;
import com.gtohjs.api.RecipeSourceSupport;
import com.gtolib.api.recipe.RecipeBuilder;
import com.gtolib.api.recipe.RecipeType;
import net.minecraft.resources.ResourceLocation;

/** Generated method-mode GT recipe. RecipeBuilder.save() is injected by the CoreMod. */
public final class GeneratedClarifierPurificationUnitRecipe63_6c_61_72_69_66_69_65_72_5f_70_75_72_69_66_69_63_61_74_69_6f_6e_5f_75_6e_69_74_ implements GTRecipeSource {
    private static final ResourceLocation RAW_ID = new ResourceLocation("gtohjs", "clarifier_purification_unit");

    public GeneratedClarifierPurificationUnitRecipe63_6c_61_72_69_66_69_65_72_5f_70_75_72_69_66_69_63_61_74_69_6f_6e_5f_75_6e_69_74_() {}

    @Override public ResourceLocation rawId() { return RAW_ID; }
    @Override public RecipeType recipeType() { return RecipeSourceSupport.recipeType("gtceu:lathe"); }

    @Override public void configure(RecipeBuilder builder) {
        builder.inputItems(RecipeSourceSupport.itemStack("gtocore:water_purification_plant", 1, ""));
        builder.outputItems(RecipeSourceSupport.itemStack("gtocore:clarifier_purification_unit", 1, ""));
        builder.EUt(30L)
                .duration(10);
    }
}
